### ISSUE TITLE
communication msg problem

### ISSUE THREAD

**Issue by manpreet05leo** [petr166/mean-chat-app#7]
project was working but both user msg cant be get or communication, msg was send but the receiver cant get the sender msg plz tell me how to work

**Comment by AshayTikekar** [comment]
@manpreet05leo
It would be great if you can provide more detailed information regarding the issue.

However my primary guess is that communication problem might be because of different value of ROOT and CHAT_PATH  variables on client and server side.

Kindly try the following before running `npm run dev`

- `export ROOT = "/api"`

-  `export CHAT_PATH = "/mean-chat-app.io"`

- change PORT = 8000 in config/index.js so that it matches on the client side

This is should solve the issue. I have addressed the same in PR  #8 .

Feel free to get back in case this does not work.

Happy Coding! 

Regards,
Ashay

**Comment by petr166** [comment]
did Ashay's solution work for you, @manpreet05leo ??
